--dba

DROP ROLE C##ROLE_DBA_OAZ29;

CREATE ROLE C##ROLE_DBA_OAZ29 NOT IDENTIFIED;

-- Object privileges granted to C##ROLE_DBA_OAZ29
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.X$PT46MP5MEPA004NE0KWN0SK0K1LN TO C##ROLE_DBA_OAZ29;
GRANT EXECUTE ON ORDSYS.CARTRIDGE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_HOME_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_INCIDENT_CORR_KEYS_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_INCIDENT_FILES_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_INCIDENT_INFO_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_INCIDENT_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARGS_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARG_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ECID_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ERRID_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTRS_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTR_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_T TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.AS_REPLAY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.CDB_XS_ACTIVE_SESSIONS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.CDB_XS_SESSIONS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.CDB_XS_SESSION_NS_ATTRIBUTES TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.CDB_XS_SESSION_ROLES TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON SYS.C##ROLE_DBA_OAZ29_REGISTRY_SQLPATCH TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON SYS.C##ROLE_DBA_OAZ29_REGISTRY_SQLPATCH_RU_INFO TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.C##ROLE_DBA_OAZ29_XS_ACTIVE_SESSIONS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.C##ROLE_DBA_OAZ29_XS_SESSIONS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.C##ROLE_DBA_OAZ29_XS_SESSION_NS_ATTRIBUTES TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.C##ROLE_DBA_OAZ29_XS_SESSION_ROLES TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ADR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ADR_APP TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_APP_CONT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_APP_CONT_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AUTO_INDEX TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AUTO_SQLTUNE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_IMMEDIATE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AWR_WAREHOUSE_SERVER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AWR_WAREHOUSE_SOURCE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_CACHEUTIL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_DNFS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_FEATURE_USAGE_REPORT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK_ARCHIVE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_FS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_GSM_FIX TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_HANG_MANAGER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_HM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ILM_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_INMEMORY_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_IR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_LOGSTDBY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_MANAGEMENT_BOOTSTRAP TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_MEMOPTIMIZE_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_MONITOR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_NETWORK_ACL_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_PERF TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_RAT_MASK TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_RESULT_CACHE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_RESUMABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ROLLING TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVER_ALERT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVER_TRACE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVICE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVICE_CONST TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVICE_ERR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVICE_PRVT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_STORAGE_MAP TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_TDB TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_TNS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_UADV_ARR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_UMF TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_UNDO_ADV TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_CAPTURE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPLAY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_WRR_STATE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_XS_PRINCIPALS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.GRANT_RDF_OWNER_DR_PRIVS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.HM_SQLTK_INTERNAL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.LOAD_UNDO_STAT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON SYS.MAP_OBJECT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.OJDS_CONTEXT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.ORD_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.OUTLN_PKG TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.RDF_NETWORK_CREATOR_PRIVS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.RESET_UNDO_STAT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL_AUX TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_ADR_INVALIDATION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_ALERT_EXT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_AMS_XACTION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION_DEF TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM_DEF TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_ACT_MAP TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_TYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_CAPTURE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_ITEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_CAPTURE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_ITEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE_ITEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DIAGV_INCIDENT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DIR_EXT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_EM_DIAG_JOB TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_EM_TARGET_INFO TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_EM_USER_ACTIVITY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_FDG_SET TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_FINDING TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_INFO TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_MESSAGE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_RECOMMENDATION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_RUN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INCCKEY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT_FILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_CONFIG TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_IMPT_DEF TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_INFO TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_PK_IMPTS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_SUMMARY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_CONFIGURATION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_COPY_LOG TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_METADATA TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_FILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_HISTORY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_INCIDENT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PKG_UNPACK_HIST TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PROGRESS_LOG TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_REMOTE_PACKAGE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_LOG_EXT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_PDB_PROBLEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_PDB_SPACE_MGMT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_PICKLEERR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_PROBLEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_RELMD_EXT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_SWEEPERR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VADR_CONTROL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG1 TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VHM_RUN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIEWCOL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT_FILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VINC_METER_INFO TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_COPY_LOG TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_METADATA TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_FILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_HISTORY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_MAIN_INT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_SIZE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_FILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_CAND TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL1 TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_MAIN_PROBLEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VNOT_EXIST_INCIDENT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPDB_PROBLEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM1 TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM2 TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET1 TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET_COUNT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_INT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_LASTINC TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VSHOWCATVIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB_I TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VTEST_EXISTS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_ACTINC TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_ACTPROB TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_INCCOUNT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_INCFCOUNT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_INC_METER_INFO_PROB TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT1 TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_NFCINC TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_SWPERRCOUNT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT INSERT, SELECT, UPDATE ON SYS.XSDB$SCHEMA_ACL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON SYS.XS_MTCACHE_INT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON XDB.DBMS_CSX_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON XDB.DBMS_XDBT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ON XDB.DBMS_XDB_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$ACL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$CHECKOUTS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$CONFIG TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$D_LINK TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$H_INDEX TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$H_LINK TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$NLOCKS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$RESCONFIG TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$RESOURCE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;

-- System privileges granted to C##ROLE_DBA_OAZ29
GRANT ADMINISTER ANY SQL TUNING SET TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ADMINISTER DATABASE TRIGGER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'C##ROLE_DBA_OAZ29', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ADMINISTER SQL TUNING SET TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ADVISOR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY ANALYTIC VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY ASSEMBLY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY ATTRIBUTE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY CLUSTER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY CUBE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY CUBE BUILD PROCESS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY CUBE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY EDITION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY HIERARCHY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY INDEX TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY INDEXTYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY LIBRARY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY MATERIALIZED VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY MEASURE FOLDER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY MINING MODEL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY OPERATOR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY OUTLINE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY PROCEDURE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY ROLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY SEQUENCE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY SQL PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY TRIGGER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ANY TYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER DATABASE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER LOCKDOWN PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER RESOURCE COST TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER ROLLBACK SEGMENT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER SESSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER SYSTEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER TABLESPACE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ALTER USER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ANALYZE ANY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ANALYZE ANY DICTIONARY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT AUDIT ANY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT AUDIT SYSTEM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT BACKUP ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT BECOME USER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CHANGE NOTIFICATION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT COMMENT ANY MINING MODEL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT COMMENT ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANALYTIC VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY ANALYTIC VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY ASSEMBLY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY CLUSTER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY CONTEXT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY CREDENTIAL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY CUBE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY CUBE BUILD PROCESS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY CUBE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY DIRECTORY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY EDITION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY HIERARCHY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY INDEX TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY INDEXTYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY JOB TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY LIBRARY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY MATERIALIZED VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY MEASURE FOLDER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY MINING MODEL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY OPERATOR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY OUTLINE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY PROCEDURE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY SEQUENCE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY SQL PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY SYNONYM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY TRIGGER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY TYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ANY VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ASSEMBLY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ATTRIBUTE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE CLUSTER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE CREDENTIAL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE CUBE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE CUBE BUILD PROCESS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE CUBE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE DATABASE LINK TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE EXTERNAL JOB TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE HIERARCHY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE INDEXTYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE JOB TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE LIBRARY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE LOCKDOWN PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE MATERIALIZED VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE MEASURE FOLDER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE MINING MODEL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE OPERATOR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE PLUGGABLE DATABASE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE PROCEDURE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE PUBLIC DATABASE LINK TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE PUBLIC SYNONYM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ROLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE ROLLBACK SEGMENT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE SEQUENCE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE SESSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE SQL TRANSLATION PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE SYNONYM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE TABLESPACE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE TRIGGER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE TYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE USER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT CREATE VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DEBUG ANY PROCEDURE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DEBUG CONNECT SESSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE ANY CUBE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE ANY MEASURE FOLDER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DELETE ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  ADMIN_OPTION => FALSE);
END;
/
GRANT DROP ANY ANALYTIC VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY ASSEMBLY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY ATTRIBUTE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY CLUSTER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY CONTEXT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY CUBE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY CUBE BUILD PROCESS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY CUBE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY DIRECTORY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY EDITION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY HIERARCHY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY INDEX TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY INDEXTYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY LIBRARY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY MATERIALIZED VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY MEASURE FOLDER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY MINING MODEL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY OPERATOR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY OUTLINE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY PROCEDURE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY ROLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY SEQUENCE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY SQL PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY SQL TRANSLATION PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY SYNONYM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY TRIGGER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY TYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ANY VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP LOCKDOWN PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP PUBLIC DATABASE LINK TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP PUBLIC SYNONYM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP ROLLBACK SEGMENT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP TABLESPACE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DROP USER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EM EXPRESS CONNECT TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  ADMIN_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY ASSEMBLY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ANY CLASS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY INDEXTYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ANY LIBRARY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ANY OPERATOR TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ANY PROCEDURE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ANY PROGRAM TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY TYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE ASSEMBLY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXPORT FULL DATABASE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT FLASHBACK ARCHIVE ADMINISTER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT FORCE ANY TRANSACTION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT FORCE TRANSACTION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT GLOBAL QUERY REWRITE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT GRANT ANY OBJECT PRIVILEGE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT GRANT ANY PRIVILEGE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT GRANT ANY ROLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT IMPORT FULL DATABASE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT INSERT ANY CUBE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT INSERT ANY MEASURE FOLDER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT INSERT ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT LOCK ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT LOGMINING TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT MANAGE ANY FILE GROUP TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'C##ROLE_DBA_OAZ29',
  ADMIN_OPTION => FALSE);
END;
/
GRANT MANAGE FILE GROUP TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT MANAGE SCHEDULER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT MANAGE TABLESPACE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT MERGE ANY VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT ON COMMIT REFRESH TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT QUERY REWRITE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT READ ANY FILE GROUP TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT READ ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT REDEFINE ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT RESTRICTED SESSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT RESUMABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ANY CUBE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ANY CUBE BUILD PROCESS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ANY CUBE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ANY MEASURE FOLDER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ANY MINING MODEL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ANY SEQUENCE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SET CONTAINER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT UNDER ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT UNDER ANY TYPE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT UNDER ANY VIEW TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT UPDATE ANY CUBE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT UPDATE ANY CUBE BUILD PROCESS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT UPDATE ANY CUBE DIMENSION TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT UPDATE ANY TABLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT USE ANY JOB RESOURCE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT USE ANY SQL TRANSLATION PROFILE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;

-- Roles granted to C##ROLE_DBA_OAZ29
GRANT CAPTURE_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DATAPUMP_EXP_FULL_DATABASE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT DATAPUMP_IMP_FULL_DATABASE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EM_EXPRESS_ALL TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT EXP_FULL_DATABASE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT GATHER_SYSTEM_STATISTICS TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT IMP_FULL_DATABASE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT JAVA_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT OLAP_C##ROLE_DBA_OAZ29 TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT OLAP_XS_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT OPTIMIZER_PROCESSING_RATE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SCHEDULER_ADMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT WM_ADMIN_ROLE TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT XC##ROLE_DBA_OAZ29DMIN TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;
GRANT XDB_SET_INVOKER TO C##ROLE_DBA_OAZ29 CONTAINER=ALL;

-- Grantees of C##ROLE_DBA_OAZ29
GRANT C##ROLE_DBA_OAZ29 TO APP_OWNER;
GRANT C##ROLE_DBA_OAZ29 TO C##OAZ26 CONTAINER=ALL;
GRANT C##ROLE_DBA_OAZ29 TO C##OAZ29 CONTAINER=ALL;
GRANT C##ROLE_DBA_OAZ29 TO C##OAZ29_2 CONTAINER=ALL;
GRANT C##ROLE_DBA_OAZ29 TO OAZ26;
GRANT C##ROLE_DBA_OAZ29 TO OAZ27;
GRANT C##ROLE_DBA_OAZ29 TO SYS WITH ADMIN OPTION CONTAINER=ALL;
GRANT C##ROLE_DBA_OAZ29 TO SYSTEM CONTAINER=ALL;
GRANT C##ROLE_DBA_OAZ29 TO TEST_C##ROLE_DBA_OAZ29;
GRANT C##ROLE_DBA_OAZ29 TO USER1;
GRANT C##ROLE_DBA_OAZ29 TO USER2;
GRANT C##ROLE_DBA_OAZ29 TO USER3;
